import "dotenv/config";

export const env = {
  port: Number(process.env.PORT ?? 4000),
  corsOrigin: process.env.CORS_ORIGIN ?? "http://localhost:3000",
  nodeEnv: process.env.NODE_ENV ?? "development",
  transcriptionProvider: process.env.TRANSCRIPTION_PROVIDER ?? "mock",
  analysisProvider: process.env.ANALYSIS_PROVIDER ?? "mock",
  chatProvider: process.env.CHAT_PROVIDER ?? process.env.ANALYSIS_PROVIDER ?? "mock",
  aiTimeoutMs: Number(process.env.AI_TIMEOUT_MS ?? 180000),
  openAiApiKey: process.env.OPENAI_API_KEY,
  adminEmail: process.env.ADMIN_EMAIL ?? "admin@orbitplan.local",
  adminPassword: process.env.ADMIN_PASSWORD ?? "OrbitPlanAdmin123!",
  sessionSecret: process.env.SESSION_SECRET ?? "dev-only-session-secret-change-me",
  googleClientId: process.env.GOOGLE_CLIENT_ID,
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET,
  googleRedirectUri: process.env.GOOGLE_REDIRECT_URI,
  jiraClientId: process.env.JIRA_CLIENT_ID,
  jiraClientSecret: process.env.JIRA_CLIENT_SECRET,
  jiraRedirectUri: process.env.JIRA_REDIRECT_URI,
  zoomClientId: process.env.ZOOM_CLIENT_ID,
  zoomClientSecret: process.env.ZOOM_CLIENT_SECRET,
  zoomRedirectUri: process.env.ZOOM_REDIRECT_URI,
  zoomScopes: process.env.ZOOM_SCOPES,
  zoomWebhookSecret: process.env.ZOOM_WEBHOOK_SECRET,
  microsoftTenantId: process.env.MICROSOFT_TENANT_ID ?? "common",
  microsoftClientId: process.env.MICROSOFT_CLIENT_ID,
  microsoftClientSecret: process.env.MICROSOFT_CLIENT_SECRET,
  microsoftRedirectUri: process.env.MICROSOFT_REDIRECT_URI,
  teamsWebhookSecret: process.env.TEAMS_WEBHOOK_SECRET,
  /** POST JSON when async meeting process finishes: { meetingId, status, error? } */
  processWebhookUrl: process.env.PROCESS_WEBHOOK_URL,
  processWebhookSecret: process.env.PROCESS_WEBHOOK_SECRET,
};
